image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: mkdir build 
- cmd: cd build    
- cmd: cmake c:\projects\source -G "Visual Studio 15 Win64"   
- cmd: cmake --build . --config "Release"
test_script:
- cmd: cd clDriver
- cmd: ctest
